version: '3.8'

services:
  orion:
    image: fiware/orion
    ports:
      - "1026:1026"
    command: -dbhost mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
