version: "3.8"

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - twin-net

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - twin-net

  orion:
    image: fiware/orion
    container_name: orion
    restart: always
    ports:
      - "1026:1026"
    command: -dbURI mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - twin-net

  sensor-simulator:
    build:
      context: ./sensor-simulator
    container_name: sensor-simulator
    depends_on:
      - orion
    networks:
      - twin-net

networks:
  twin-net:
    driver: bridge
